name: project3_objectbox
description: "A project for observing ObjectBox."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  build_runner: ^2.4.11
  flutter:
    sdk: flutter
  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  objectbox_flutter_libs: ^4.0.3
  build_runner: any
  objectbox_generator: any

flutter:
  uses-material-design: true
